### ISSUE TITLE
Motion Segmentation Results

### ISSUE THREAD

**Issue by davezdeng8** [mercedes-benz/selfsupervised_flow#11]
Hi, in the main paper, the reported mIoU on KITTI Scene Flow is 59.5, but in the supplement it seems to be 42.9. Which number is correct? Thanks!

**Comment by baurst** [comment]
Thank you for your interest. If I recall correctly, I think basically what you are referring to is the difference between what we call "Opt acc & opt mIoU" and "acc/mIoU". The optimal scores for scene flow and motion segmentation are not necessarily obtained at the same threshold value, which is why we provide both numbers. If I recalll correctly, mIoU refers to the performance of the network at the learned threshold with the KNN end point error proxy, so ideally this would be at the optimal scene flow performance. In contrast, opt mIoU refers to the optimal threshold for segmentation performance, regardless of resulting scene flow performance. This is explained in more detail in section 3 "Moving Classification Threshold" and Figure 2 in the supplementary material. I hope this helps. Please feel free to reopen if you have further questions.
